### ISSUE TITLE
多证书情况下，如果客户端不支持SNI，默认使用哪一个证书？

### ISSUE THREAD

**Issue by wordgod123** [alibaba/tengine#1012]
比如服务器配置了www.a.com.key和www.b.com.key，如果client不支持SNI，服务器会使用哪一个证书？有什么规则没有？

**Comment by taoyuanyuan** [comment]
首先使用default server 的证书，如果没有配置default,用配置靠前server的证书。




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            Yang Tian
                            
                            
                                
                                    邮箱：linuxty@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年02月08日 17:08，wordgod123 写道： 比如服务器配置了www.a.com.key和www.b.com.key，如果client不支持SNI，服务器会使用哪一个证书？有什么规则没有？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alibaba/tengine","title":"alibaba/tengine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alibaba/tengine"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"多证书情况下，如果客户端不支持SNI，默认使用哪一个证书？ (#1012)"}],"action":{"name":"View Issue","url":"https://github.com/alibaba/tengine/issues/1012"}}}

**Comment by wordgod123** [comment]
@taoyuanyuan 我的server配置文件放在conf.d目录下面，怎么判断哪个证书靠前？是根据比如我有a.conf，证书名为www.bbs.com.crt,  另一个配置文件为b.conf，里面证书为www.ali.com.crt，这种情况下哪个证书靠前?

**Comment by taoyuanyuan** [comment]
```include  conf.d/*.conf; ```
这样配置的话，文件名会根据ascII码排序加载， a.conf将先加载，所以a.conf证书靠前。

**Comment by wordgod123** [comment]
@taoyuanyuan 非常感谢
