### ISSUE TITLE
tengine2.2.2+openssl1.1.0h 编译错误

### ISSUE THREAD

**Issue by okyangyi** [alibaba/tengine#1066]
具体报错：
src/http/modules/ngx_http_dyups_module.c
src/http/modules/ngx_http_dyups_module.c: In function ‘ngx_http_dyups_set_peer_session’:
src/http/modules/ngx_http_dyups_module.c:2551: error: dereferencing pointer to incomplete type
src/http/modules/ngx_http_dyups_module.c: In function ‘ngx_http_dyups_save_peer_session’:
src/http/modules/ngx_http_dyups_module.c:2572: error: dereferencing pointer to incomplete type
src/http/modules/ngx_http_dyups_module.c:2579: error: dereferencing pointer to incomplete type
make[1]: *** [objs/src/http/modules/ngx_http_dyups_module.o] Error 1
make[1]: Leaving directory `/opt/soft/tengine-2.2.2'
make: *** [build] Error 2

编译参数：./configure --prefix=/opt/soft/nginx --conf-path=/opt/soft/nginx/main-conf/nginx.conf --error-log-path=/opt/log/nginx/error.log --http-log-path=/opt/log/nginx/access.log --pid-path=/opt/soft/nginx/run/nginx.pid --lock-path=/opt/soft/nginx/run/nginx.lock --http-client-body-temp-path=/opt/soft/nginx/cache/nginx/client_temp --http-proxy-temp-path=/opt/soft/nginx/cache/nginx/proxy_temp --http-fastcgi-temp-path=/opt/soft/nginx/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/opt/soft/nginx/cache/nginx/uwsgi_temp --http-scgi-temp-path=/opt/soft/nginx/cache/nginx/scgi_temp --user=work --group=work --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --with-http_concat_module --with-http_image_filter_module --with-http_lua_module --with-debug --add-module=/opt/soft/source/ngx_devel_kit/ --add-module=/opt/soft/source/form-input-nginx-module/ --add-module=/opt/soft/source/echo-nginx-module --add-module=/opt/soft/source/set-misc-nginx-module --with-http_dyups_module --with-http_dyups_lua_api --with-http_v2_module --with-http_ssl_module --with-openssl-async --with-http_v2_module --with-cc-opt='-DNGX_SECURE_MEM -I/opt/soft/openssl/include -Wno-error=deprecated-declarations' --with-ld-opt="-Wl,-rpath,/opt/soft/openssl/lib -L/opt/soft/openssl/lib"

注：/opt/soft/openssl 目录为openssl1.1.0h安装目录

请问如何解决此问题，谢谢

**Comment by wangfakang** [comment]
@okyangyi  由于高OpenSSL里面的一些结构体定义没有放在include的头文件了，需要强制调用OpenSSL的一些API来访问，如下代码片段中的`ssl_session->references`是不允许直接指针访问的，需要使用特定的OpenSSL API访问，我们将在下个版本中修复。

```
    ngx_log_debug2(NGX_LOG_DEBUG_HTTP, pc->log, 0,
                   "set session: %p:%d",
                   ssl_session, ssl_session ? ssl_session->references : 0);
```

**Comment by wangfakang** [comment]
@okyangyi  https://github.com/alibaba/tengine/pull/1190

**Comment by chobits** [comment]
hi @okyangyi 

fixed in latest master ( merged pr: https://github.com/alibaba/tengine/pull/1190), please check it!

Note that current master is new version 2.3.x, based on nginx 1.15.x, its large updating. Check warning as following:

# WARNING

Note that this version is slightly not backwards compatible, some tengine features have been replaced by nginx offical.  check the following list:
1. `--with-http_slice_module` configure option now works for [nginx slice module](http://nginx.org/en/docs/http/ngx_http_slice_module.html). Use `--add-module=modules/ngx_http_slice_module` for original [tengine slice module](http://tengine.taobao.org/document/http_slice.html).
2. Removed Tengine DSO feature, use [nginx dynamic modules feature](https://www.nginx.com/resources/wiki/extending/converting/) instead.
3. Removed `reuse_port` directive in `event {}` block, use [`listen .. reuseport;` directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#listen) instead.
4. Extract the tengine modules to modules dir, if you need to use that module then use `--add-module=modules/xxx_module_name` way to compile.
5. The request counting logic for limit_req is consistent with the Nginx official. Now requests with all empty variable in `limit_req_zone` are not accounted. Original tengine does not account requests with any empty variable.
